plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.example.ecommerce'
version = '1.0.0-SNAPSHOT'
description = 'ecomm-app-java'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.springboot.starter
    implementation libs.springboot.starter.web
    implementation libs.springboot.starter.security
    implementation libs.springboot.starter.data.mongodb
    testImplementation libs.springboot.starter.test
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
}

